# Generated by Django 2.0.2 on 2018-03-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer_shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(max_length=30)),
                ('union_council', models.CharField(max_length=30)),
                ('upazila', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('division', models.CharField(max_length=30)),
            ],
        ),
    ]
