# Generated by Django 2.0.2 on 2018-03-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizer_shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizer_shop',
            name='id',
        ),
        migrations.AddField(
            model_name='fertilizer_shop',
            name='memid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
