# Generated by Django 2.0.2 on 2018-03-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizer_shops', '0002_auto_20180305_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilizer_shop',
            old_name='memid',
            new_name='id',
        ),
    ]
