# Generated by Django 2.0.2 on 2018-03-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizer_shops', '0003_auto_20180305_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer_shop',
            name='district',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fertilizer_shop',
            name='division',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fertilizer_shop',
            name='union_council',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fertilizer_shop',
            name='upazila',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fertilizer_shop',
            name='village',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
