# Generated by Django 2.0.2 on 2018-03-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizer_shops', '0004_auto_20180305_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer_shop',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
