; -- Sokoban.iss --

; INNO Setup Script File
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING .ISS SCRIPT FILES!

[Setup]
AppName=SokoSkinner Skins for Sokoban YASC
AppVerName=SokoSkinner Skins
AppCopyright=Copyright © 2017 by Brian Damgaard
DefaultDirName={pf}\BDSokobanYASC
DefaultGroupName=Sokoban
;UninstallDisplayIcon={app}\Sokoban.exe
; uncomment the following line if you want your installation to run on NT 3.51 too.
; MinVersion=4,3.51
;MessagesFile=Sokoban.isl
;AppMutex=BDSokobanYASCMutex,Global\BDSokobanYASCMutex
DirExistsWarning=no
DisableStartupPrompt=yes
DisableDirPage=yes
DisableProgramGroupPage=yes
DisableFinishedPage=no
WizardStyle=modern
WindowVisible=no
;SetupIconFile=Setup.ico
;PrivilegesRequired=admin

[Files]
Source: "SokoSkinner ReadMe.txt"; DestDir: "{userdocs}\Sokoban\Sokoban YASC"; Flags: isreadme
Source: "300.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "A Day at the Races.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "A Knight's Heart.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Alien Encounters.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Anarchy.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Anubis.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Apple Girl.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Apprentice.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Aqua Maiden.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Arab Princess .png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Auto Tech.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Autumn Rogue.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Baby Lugi.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Baby Mario.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Bad Dog.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Bane.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Banker's Hours.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Bartender.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Biohazard.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Blacksmith.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Blood Stone.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Blue Bubble Bobble.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Blue Dragon.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Blue Knight Quest.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Blue Knight.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Bomb Squad.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "BomberMan.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Bone Crusher.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Bowling.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Bowser.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Breakfast at Grandma's.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Brokenhearted.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Buffalo.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Bunny Girl .png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Cake Baker.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Candy Girl.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Captain Spaulding.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Chuck Rock.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Coffee is Served.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Cookie Baker.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Cops & Robbers.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Courage the Cowardly Dog.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Cupcake Girl.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Dante's Heart.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Dark Elf Apprentice.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Dark Wizard 2.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Dark Wizard.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Davy Jones Locker.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Demon Fire.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Demon Knight.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Demon's Brew.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Devil May Cry.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Dracula.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Dragon Blood Knight.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Dragon Eye 2.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Dragon Eye.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Dragon Warrior.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Duncan Donut.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Elf Knight.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Elf Prince .png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Emerald Knight.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Evil Clown.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Evil Genie.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Family Guy Stewie.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Fire Priest .png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Flower Girl.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Frog King.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Frog Prince.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Gate Keeper.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Ghost Pirate.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Gnome.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Gold Bubble Bobble.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Graduation.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Granny's Cookies.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Green Bubble Bobble.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Green Dragon.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Green Duke.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Green Knight.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Head Hunter.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Hungry Monster.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Ice Dragon.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Ice Mage.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Island Girl.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Jewel Priestess.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Kitty Girl.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Knight in Shining Armor.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Knight's Quest 2.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Knight's Quest 3.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Knight's Quest 4.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Knight's Quest.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Lady in Waiting.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Last Tango.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Library.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Locked Away.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Lord of the Ring.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "LOTR Elf.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Luck of the Irish.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Lugi.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Magician.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Maji.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "McDonald.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Minotaur.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Monk.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Monkey.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Monopoly.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Monsters Inc. Sully.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Mummy.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Music Lover.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Nosferatu.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Old Mage.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Orc Knight.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Orc Warrior.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Orc.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Phantom of the Opera.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Phantom.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Pink Bubble Bobble.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Pink Maiden.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Pirate Treasure.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Pizza Chef.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Pizza Hut.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Playboy Bunny.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Poison Ivy.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Pokemon.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Police Officer.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Predator.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Princess Zelda.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Pumpkin King.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Pumpkin Man.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Puppy Luv.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Purple Maiden.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Quest Knight .png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Red Dragon.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Red Mage.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Red Wizard.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Robot.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Roman Soldier.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Ruins.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Rum Runner.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Sea Captain.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Seamstress.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Shield Knight.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Shield Maiden.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Siren Call.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Skull Warrior.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Snake Bliskin.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Snow Ranger.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "South Park Cartman.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "SpellCaster.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Spider.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Spring Rogue.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Squire.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Star Wars.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Strawberry Girl.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Strawberry Jam.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Superman.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Sushi Girl.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Teen Queen.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "The Gardener.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "The Legend of Zelda.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Thief.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Tomb Raider.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Toxin.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Toy Box.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Trash Day.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Tree Imp.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Trucker.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Tug Boat Captain.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Vampire Hunter .png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Vampire.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Waitress.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Wario.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Werewolf.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "White Mage.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Winter Rogue.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Witch King.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Wizard Quest.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Woodland Paige.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Woodsman.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Yoshi.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Young Prince.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Yuna.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Zelda's Link.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Source: "Zombie Lunch.png"; DestDir: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"

[Icons]
;Name: "{group}\Sokoban YASC"; Filename: "{app}\Sokoban.exe"
;Name: "{userdesktop}\Sokoban YASC"; Filename: "{app}\Sokoban.exe"

[Registry]
;Root: HKCU; Subkey: "Software\BDSokobanYASC"; Flags: uninsdeletekey 
;Root: HKLM; Subkey: "Software\BDSokobanYASC"; Flags: uninsdeletekey

[Run]
;Filename: "{app}\Sokoban.exe"; Description: "{cm:LaunchProgram,Sokoban YASC}"; Flags: nowait postinstall skipifsilent

[UninstallDelete] 
Type: filesandordirs; Name: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner\*.*"
Type: files; Name: "{userdocs}\Sokoban\Sokoban YASC\SokoSkinner ReadMe.txt"
Type: dirifempty; Name: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins\SokoSkinner"
Type: dirifempty; Name: "{userdocs}\Sokoban\Sokoban YASC\Skins\Common Skins"
Type: dirifempty; Name: "{userdocs}\Sokoban\Sokoban YASC\Skins"
Type: dirifempty; Name: "{userdocs}\Sokoban\Sokoban YASC"
Type: dirifempty; Name: "{userdocs}\Sokoban"
