create table books_books_publisher (
	name  VARCHAR(50),
	address VARCHAR(50),
	city VARCHAR(50),
	state_province VARCHAR(50),
	country VARCHAR(50),
	website VARCHAR(1000)
);
INSERT INTO books_publisher (name , address, city, state_province, country, website) VALUES ('Abatz', '3765 Warrior Junction', 'Liuliping', null, 'China', 'https://imgur.com/commodo/placerat/praesent/blandit/nam.jsp?nisi=id&volutpat=massa&eleifend=id&donec=nisl&ut=venenatis&dolor=lacinia&morbi=aenean&vel=sit&lectus=amet&in=justo&quam=morbi&fringilla=ut&rhoncus=odio&mauris=cras&enim=mi&leo=pede&rhoncus=malesuada&sed=in&vestibulum=imperdiet&sit=et&amet=commodo&cursus=vulputate&id=justo&turpis=in&integer=blandit&aliquet=ultrices&massa=enim&id=lorem&lobortis=ipsum&convallis=dolor&tortor=sit&risus=amet&dapibus=consectetuer&augue=adipiscing&vel=elit&accumsan=proin&tellus=interdum&nisi=mauris&eu=non&orci=ligula&mauris=pellentesque&lacinia=ultrices&sapien=phasellus&quis=id&libero=sapien&nullam=in&sit=sapien&amet=iaculis&turpis=congue&elementum=vivamus&ligula=metus&vehicula=arcu&consequat=adipiscing&morbi=molestie&a=hendrerit&ipsum=at&integer=vulputate&a=vitae&nibh=nisl&in=aenean&quis=lectus&justo=pellentesque&maecenas=eget&rhoncus=nunc&aliquam=donec&lacus=quis&morbi=orci&quis=eget&tortor=orci&id=vehicula&nulla=condimentum&ultrices=curabitur&aliquet=in&maecenas=libero&leo=ut&odio=massa&condimentum=volutpat&id=convallis&luctus=morbi&nec=odio&molestie=odio&sed=elementum&justo=eu&pellentesque=interdum&viverra=eu&pede=tincidunt&ac=in&diam=leo&cras=maecenas&pellentesque=pulvinar&volutpat=lobortis&dui=est&maecenas=phasellus&tristique=sit&est=amet');
INSERT INTO books_publisher (name , address, city, state_province, country, website) VALUES ('Mita', '17 Bluestem Way', 'Sofia', null, 'Bulgaria', 'https://intel.com/nisi/at/nibh/in.png?in=velit&consequat=eu&ut=est&nulla=congue&sed=elementum&accumsan=in&felis=hac&ut=habitasse&at=platea&dolor=dictumst&quis=morbi&odio=vestibulum&consequat=velit&varius=id&integer=pretium&ac=iaculis&leo=diam&pellentesque=erat&ultrices=fermentum&mattis=justo&odio=nec&donec=condimentum&vitae=neque&nisi=sapien&nam=placerat');
INSERT INTO books_publisher (name , address, city, state_province, country, website) VALUES ('Kazu', '22 Independence Point', 'Seymchan', null, 'Russia', 'http://craigslist.org/morbi/porttitor/lorem/id/ligula.jsp?nulla=mauris&ultrices=eget&aliquet=massa&maecenas=tempor&leo=convallis&odio=nulla&condimentum=neque&id=libero&luctus=convallis&nec=eget&molestie=eleifend&sed=luctus&justo=ultricies&pellentesque=eu&viverra=nibh&pede=quisque&ac=id&diam=justo&cras=sit&pellentesque=amet&volutpat=sapien&dui=dignissim&maecenas=vestibulum&tristique=vestibulum&est=ante&et=ipsum&tempus=primis&semper=in&est=faucibus&quam=orci&pharetra=luctus&magna=et&ac=ultrices&consequat=posuere&metus=cubilia&sapien=curae&ut=nulla&nunc=dapibus&vestibulum=dolor&ante=vel&ipsum=est&primis=donec&in=odio&faucibus=justo&orci=sollicitudin&luctus=ut&et=suscipit');
INSERT INTO books_publisher (name , address, city, state_province, country, website) VALUES ('Skidoo', '915 Dorton Parkway', 'Tenri', null, 'Japan', 'https://ebay.co.uk/justo/in/hac/habitasse.html?in=ut&faucibus=odio&orci=cras&luctus=mi&et=pede&ultrices=malesuada&posuere=in&cubilia=imperdiet&curae=et&donec=commodo&pharetra=vulputate&magna=justo&vestibulum=in&aliquet=blandit&ultrices=ultrices&erat=enim&tortor=lorem&sollicitudin=ipsum&mi=dolor&sit=sit&amet=amet&lobortis=consectetuer&sapien=adipiscing&sapien=elit&non=proin&mi=interdum&integer=mauris&ac=non&neque=ligula&duis=pellentesque&bibendum=ultrices&morbi=phasellus&non=id&quam=sapien&nec=in&dui=sapien&luctus=iaculis&rutrum=congue&nulla=vivamus&tellus=metus&in=arcu&sagittis=adipiscing&dui=molestie&vel=hendrerit&nisl=at&duis=vulputate&ac=vitae&nibh=nisl&fusce=aenean&lacus=lectus&purus=pellentesque&aliquet=eget&at=nunc&feugiat=donec&non=quis&pretium=orci&quis=eget&lectus=orci&suspendisse=vehicula&potenti=condimentum&in=curabitur&eleifend=in&quam=libero&a=ut&odio=massa&in=volutpat&hac=convallis&habitasse=morbi&platea=odio&dictumst=odio&maecenas=elementum&ut=eu&massa=interdum&quis=eu&augue=tincidunt&luctus=in&tincidunt=leo&nulla=maecenas&mollis=pulvinar&molestie=lobortis&lorem=est&quisque=phasellus&ut=sit&erat=amet&curabitur=erat&gravida=nulla&nisi=tempus&at=vivamus&nibh=in&in=felis&hac=eu&habitasse=sapien&platea=cursus&dictumst=vestibulum');
INSERT INTO books_publisher (name , address, city, state_province, country, website) VALUES ('Minyx', '40 High Crossing Park', 'Minas de Marcona', null, 'Peru', 'https://multiply.com/consequat/nulla/nisl/nunc/nisl/duis/bibendum.jpg?sed=habitasse&tristique=platea&in=dictumst&tempus=aliquam&sit=augue&amet=quam&sem=sollicitudin&fusce=vitae&consequat=consectetuer&nulla=eget&nisl=rutrum&nunc=at&nisl=lorem&duis=integer&bibendum=tincidunt&felis=ante&sed=vel&interdum=ipsum&venenatis=praesent&turpis=blandit&enim=lacinia&blandit=erat&mi=vestibulum&in=sed&porttitor=magna&pede=at&justo=nunc&eu=commodo&massa=placerat&donec=praesent&dapibus=blandit&duis=nam&at=nulla&velit=integer&eu=pede&est=justo&congue=lacinia&elementum=eget&in=tincidunt');
INSERT INTO books_publisher (name , address, city, state_province, country, website) VALUES ('Meevee', '388 Old Shore Junction', 'Bi’r Ḩāt', null, 'Yemen', 'https://hugedomains.com/et/commodo/vulputate.xml?luctus=donec&et=dapibus&ultrices=duis&posuere=at&cubilia=velit&curae=eu&duis=est&faucibus=congue&accumsan=elementum&odio=in&curabitur=hac&convallis=habitasse&duis=platea&consequat=dictumst&dui=morbi&nec=vestibulum&nisi=velit&volutpat=id&eleifend=pretium&donec=iaculis&ut=diam&dolor=erat&morbi=fermentum&vel=justo&lectus=nec&in=condimentum&quam=neque&fringilla=sapien&rhoncus=placerat&mauris=ante&enim=nulla&leo=justo&rhoncus=aliquam&sed=quis&vestibulum=turpis&sit=eget&amet=elit&cursus=sodales&id=scelerisque&turpis=mauris&integer=sit&aliquet=amet&massa=eros&id=suspendisse&lobortis=accumsan&convallis=tortor&tortor=quis&risus=turpis&dapibus=sed&augue=ante&vel=vivamus&accumsan=tortor&tellus=duis&nisi=mattis&eu=egestas&orci=metus&mauris=aenean&lacinia=fermentum&sapien=donec&quis=ut&libero=mauris&nullam=eget&sit=massa&amet=tempor&turpis=convallis&elementum=nulla&ligula=neque&vehicula=libero&consequat=convallis&morbi=eget&a=eleifend&ipsum=luctus&integer=ultricies&a=eu&nibh=nibh&in=quisque&quis=id&justo=justo&maecenas=sit&rhoncus=amet&aliquam=sapien&lacus=dignissim&morbi=vestibulum&quis=vestibulum&tortor=ante');
INSERT INTO books_publisher (name , address, city, state_province, country, website) VALUES ('Photobug', '9 Nancy Parkway', 'Kurunegala', null, 'Sri Lanka', 'https://themeforest.net/nulla/suspendisse/potenti/cras/in.jpg?imperdiet=vulputate&sapien=justo&urna=in&pretium=blandit&nisl=ultrices&ut=enim&volutpat=lorem&sapien=ipsum&arcu=dolor&sed=sit&augue=amet&aliquam=consectetuer&erat=adipiscing&volutpat=elit&in=proin&congue=interdum');
INSERT INTO books_publisher (name , address, city, state_province, country, website) VALUES ('Midel', '17083 Division Terrace', 'Insiza', null, 'Zimbabwe', 'https://columbia.edu/elit/proin/risus.aspx?eget=lobortis&congue=ligula&eget=sit&semper=amet&rutrum=eleifend&nulla=pede&nunc=libero&purus=quis&phasellus=orci&in=nullam&felis=molestie&donec=nibh&semper=in&sapien=lectus&a=pellentesque&libero=at&nam=nulla&dui=suspendisse&proin=potenti&leo=cras&odio=in&porttitor=purus&id=eu&consequat=magna&in=vulputate&consequat=luctus&ut=cum&nulla=sociis&sed=natoque&accumsan=penatibus&felis=et&ut=magnis&at=dis&dolor=parturient&quis=montes&odio=nascetur&consequat=ridiculus&varius=mus&integer=vivamus&ac=vestibulum&leo=sagittis&pellentesque=sapien&ultrices=cum&mattis=sociis&odio=natoque&donec=penatibus&vitae=et&nisi=magnis&nam=dis&ultrices=parturient&libero=montes&non=nascetur&mattis=ridiculus&pulvinar=mus&nulla=etiam&pede=vel&ullamcorper=augue&augue=vestibulum&a=rutrum&suscipit=rutrum&nulla=neque&elit=aenean&ac=auctor&nulla=gravida');
INSERT INTO books_publisher (name , address, city, state_province, country, website) VALUES ('Edgewire', '8196 Oneill Parkway', 'Qiansuo', null, 'China', 'https://twitter.com/nisi/volutpat/eleifend/donec/ut/dolor.png?vivamus=mauris&in=eget&felis=massa&eu=tempor&sapien=convallis&cursus=nulla&vestibulum=neque&proin=libero&eu=convallis&mi=eget&nulla=eleifend&ac=luctus&enim=ultricies&in=eu&tempor=nibh&turpis=quisque&nec=id&euismod=justo&scelerisque=sit&quam=amet&turpis=sapien&adipiscing=dignissim&lorem=vestibulum&vitae=vestibulum&mattis=ante&nibh=ipsum&ligula=primis&nec=in&sem=faucibus&duis=orci&aliquam=luctus&convallis=et&nunc=ultrices&proin=posuere&at=cubilia&turpis=curae&a=nulla&pede=dapibus&posuere=dolor&nonummy=vel&integer=est&non=donec&velit=odio&donec=justo&diam=sollicitudin&neque=ut&vestibulum=suscipit&eget=a&vulputate=feugiat&ut=et&ultrices=eros&vel=vestibulum&augue=ac&vestibulum=est&ante=lacinia&ipsum=nisi&primis=venenatis&in=tristique&faucibus=fusce&orci=congue&luctus=diam&et=id&ultrices=ornare&posuere=imperdiet&cubilia=sapien&curae=urna&donec=pretium&pharetra=nisl&magna=ut&vestibulum=volutpat&aliquet=sapien&ultrices=arcu&erat=sed&tortor=augue&sollicitudin=aliquam&mi=erat&sit=volutpat&amet=in');
INSERT INTO books_publisher (name , address, city, state_province, country, website) VALUES ('Meedoo', '0 Holy Cross Drive', 'Sacramento', 'California', 'United States', 'http://sakura.ne.jp/turpis/elementum/ligula/vehicula/consequat/morbi.html?odio=vestibulum&consequat=ante&varius=ipsum&integer=primis&ac=in&leo=faucibus&pellentesque=orci&ultrices=luctus&mattis=et');
INSERT INTO books_publisher (name , address, city, state_province, country, website) VALUES ('Babblestorm', '32 4th Road', 'Hanušovice', null, 'Czech Republic', 'http://hostgator.com/adipiscing/lorem/vitae/mattis/nibh.aspx?fringilla=vel&rhoncus=lectus&mauris=in&enim=quam&leo=fringilla&rhoncus=rhoncus&sed=mauris&vestibulum=enim&sit=leo&amet=rhoncus&cursus=sed&id=vestibulum&turpis=sit&integer=amet&aliquet=cursus&massa=id&id=turpis&lobortis=integer&convallis=aliquet&tortor=massa&risus=id&dapibus=lobortis&augue=convallis&vel=tortor&accumsan=risus&tellus=dapibus&nisi=augue&eu=vel&orci=accumsan&mauris=tellus&lacinia=nisi&sapien=eu&quis=orci&libero=mauris&nullam=lacinia&sit=sapien&amet=quis&turpis=libero&elementum=nullam&ligula=sit&vehicula=amet&consequat=turpis&morbi=elementum&a=ligula&ipsum=vehicula&integer=consequat&a=morbi&nibh=a&in=ipsum&quis=integer&justo=a&maecenas=nibh&rhoncus=in&aliquam=quis&lacus=justo&morbi=maecenas&quis=rhoncus&tortor=aliquam&id=lacus&nulla=morbi&ultrices=quis&aliquet=tortor&maecenas=id&leo=nulla&odio=ultrices&condimentum=aliquet&id=maecenas&luctus=leo&nec=odio&molestie=condimentum&sed=id&justo=luctus&pellentesque=nec&viverra=molestie&pede=sed&ac=justo&diam=pellentesque&cras=viverra&pellentesque=pede&volutpat=ac&dui=diam&maecenas=cras&tristique=pellentesque&est=volutpat&et=dui&tempus=maecenas&semper=tristique&est=est&quam=et&pharetra=tempus&magna=semper&ac=est&consequat=quam');
INSERT INTO books_publisher (name , address, city, state_province, country, website) VALUES ('Jaloo', '02875 Algoma Drive', 'Trondheim', 'Sor-Trondelag', 'Norway', 'http://google.com/pretium/iaculis/diam/erat.xml?nulla=molestie&ut=nibh&erat=in&id=lectus&mauris=pellentesque&vulputate=at&elementum=nulla&nullam=suspendisse&varius=potenti&nulla=cras&facilisi=in&cras=purus&non=eu&velit=magna&nec=vulputate&nisi=luctus&vulputate=cum&nonummy=sociis&maecenas=natoque&tincidunt=penatibus&lacus=et&at=magnis&velit=dis&vivamus=parturient&vel=montes&nulla=nascetur&eget=ridiculus&eros=mus&elementum=vivamus&pellentesque=vestibulum&quisque=sagittis&porta=sapien&volutpat=cum&erat=sociis&quisque=natoque&erat=penatibus&eros=et&viverra=magnis&eget=dis&congue=parturient&eget=montes&semper=nascetur&rutrum=ridiculus&nulla=mus&nunc=etiam&purus=vel&phasellus=augue&in=vestibulum&felis=rutrum&donec=rutrum&semper=neque&sapien=aenean&a=auctor&libero=gravida&nam=sem&dui=praesent&proin=id&leo=massa&odio=id&porttitor=nisl&id=venenatis&consequat=lacinia&in=aenean&consequat=sit&ut=amet&nulla=justo&sed=morbi&accumsan=ut&felis=odio&ut=cras&at=mi&dolor=pede');
INSERT INTO books_publisher (name , address, city, state_province, country, website) VALUES ('Zoomcast', '220 Reindahl Hill', 'Nangxian', null, 'China', 'http://nymag.com/a/feugiat/et/eros/vestibulum/ac.js?vestibulum=volutpat&ac=convallis&est=morbi&lacinia=odio&nisi=odio&venenatis=elementum&tristique=eu&fusce=interdum&congue=eu&diam=tincidunt&id=in&ornare=leo&imperdiet=maecenas&sapien=pulvinar&urna=lobortis&pretium=est&nisl=phasellus&ut=sit&volutpat=amet&sapien=erat&arcu=nulla&sed=tempus&augue=vivamus&aliquam=in&erat=felis&volutpat=eu&in=sapien&congue=cursus&etiam=vestibulum&justo=proin&etiam=eu&pretium=mi&iaculis=nulla&justo=ac&in=enim&hac=in&habitasse=tempor&platea=turpis&dictumst=nec&etiam=euismod&faucibus=scelerisque&cursus=quam&urna=turpis&ut=adipiscing');
INSERT INTO books_publisher (name , address, city, state_province, country, website) VALUES ('Tazz', '099 Holmberg Place', 'Ibaraki', null, 'Japan', 'https://google.de/interdum/mauris/non/ligula.png?neque=vestibulum&duis=proin&bibendum=eu&morbi=mi&non=nulla&quam=ac&nec=enim&dui=in&luctus=tempor&rutrum=turpis&nulla=nec&tellus=euismod&in=scelerisque&sagittis=quam&dui=turpis&vel=adipiscing&nisl=lorem&duis=vitae&ac=mattis&nibh=nibh&fusce=ligula&lacus=nec&purus=sem&aliquet=duis&at=aliquam&feugiat=convallis&non=nunc&pretium=proin&quis=at&lectus=turpis&suspendisse=a&potenti=pede&in=posuere&eleifend=nonummy&quam=integer&a=non&odio=velit&in=donec&hac=diam&habitasse=neque&platea=vestibulum&dictumst=eget&maecenas=vulputate&ut=ut&massa=ultrices&quis=vel&augue=augue&luctus=vestibulum&tincidunt=ante&nulla=ipsum&mollis=primis&molestie=in&lorem=faucibus&quisque=orci&ut=luctus&erat=et&curabitur=ultrices&gravida=posuere&nisi=cubilia&at=curae&nibh=donec&in=pharetra&hac=magna&habitasse=vestibulum&platea=aliquet&dictumst=ultrices&aliquam=erat');
INSERT INTO books_publisher (name , address, city, state_province, country, website) VALUES ('Demivee', '6795 Mosinee Center', 'As Sayyānī', null, 'Yemen', 'https://over-blog.com/sem/mauris.jsp?felis=ipsum&fusce=primis&posuere=in&felis=faucibus&sed=orci&lacus=luctus&morbi=et&sem=ultrices&mauris=posuere');
INSERT INTO books_publisher (name , address, city, state_province, country, website) VALUES ('Youtags', '626 Banding Parkway', 'Norfolk', 'Virginia', 'United States', 'https://sbwire.com/elementum.xml?nulla=vulputate&neque=elementum&libero=nullam&convallis=varius&eget=nulla&eleifend=facilisi&luctus=cras&ultricies=non&eu=velit&nibh=nec&quisque=nisi&id=vulputate&justo=nonummy&sit=maecenas&amet=tincidunt&sapien=lacus&dignissim=at&vestibulum=velit&vestibulum=vivamus&ante=vel&ipsum=nulla&primis=eget&in=eros&faucibus=elementum&orci=pellentesque&luctus=quisque&et=porta&ultrices=volutpat&posuere=erat&cubilia=quisque&curae=erat&nulla=eros&dapibus=viverra&dolor=eget&vel=congue&est=eget&donec=semper&odio=rutrum&justo=nulla&sollicitudin=nunc&ut=purus&suscipit=phasellus&a=in&feugiat=felis&et=donec&eros=semper&vestibulum=sapien&ac=a&est=libero&lacinia=nam&nisi=dui&venenatis=proin&tristique=leo&fusce=odio&congue=porttitor&diam=id&id=consequat&ornare=in&imperdiet=consequat&sapien=ut&urna=nulla&pretium=sed&nisl=accumsan&ut=felis&volutpat=ut&sapien=at&arcu=dolor&sed=quis&augue=odio&aliquam=consequat&erat=varius&volutpat=integer&in=ac&congue=leo&etiam=pellentesque&justo=ultrices&etiam=mattis&pretium=odio&iaculis=donec&justo=vitae&in=nisi&hac=nam&habitasse=ultrices&platea=libero&dictumst=non&etiam=mattis');
INSERT INTO books_publisher (name , address, city, state_province, country, website) VALUES ('Aivee', '2 Kenwood Pass', 'Sussex', 'New Brunswick', 'Canada', 'http://prweb.com/tortor/eu.js?odio=libero&curabitur=ut&convallis=massa&duis=volutpat&consequat=convallis&dui=morbi&nec=odio&nisi=odio&volutpat=elementum&eleifend=eu&donec=interdum&ut=eu&dolor=tincidunt&morbi=in&vel=leo&lectus=maecenas&in=pulvinar&quam=lobortis&fringilla=est&rhoncus=phasellus&mauris=sit&enim=amet&leo=erat');
INSERT INTO books_publisher (name , address, city, state_province, country, website) VALUES ('Babbleblab', '43228 Dryden Trail', 'Shalang', null, 'China', 'http://usa.gov/sem.xml?volutpat=congue&dui=eget&maecenas=semper&tristique=rutrum&est=nulla&et=nunc&tempus=purus&semper=phasellus&est=in&quam=felis&pharetra=donec&magna=semper&ac=sapien&consequat=a&metus=libero&sapien=nam&ut=dui&nunc=proin&vestibulum=leo&ante=odio&ipsum=porttitor&primis=id&in=consequat&faucibus=in&orci=consequat&luctus=ut&et=nulla&ultrices=sed&posuere=accumsan&cubilia=felis&curae=ut&mauris=at&viverra=dolor&diam=quis&vitae=odio&quam=consequat&suspendisse=varius&potenti=integer&nullam=ac&porttitor=leo&lacus=pellentesque&at=ultrices&turpis=mattis&donec=odio&posuere=donec&metus=vitae&vitae=nisi&ipsum=nam&aliquam=ultrices&non=libero&mauris=non&morbi=mattis&non=pulvinar&lectus=nulla&aliquam=pede&sit=ullamcorper&amet=augue&diam=a&in=suscipit&magna=nulla&bibendum=elit&imperdiet=ac&nullam=nulla&orci=sed&pede=vel&venenatis=enim&non=sit&sodales=amet&sed=nunc&tincidunt=viverra&eu=dapibus&felis=nulla&fusce=suscipit&posuere=ligula&felis=in&sed=lacus&lacus=curabitur&morbi=at&sem=ipsum&mauris=ac&laoreet=tellus&ut=semper&rhoncus=interdum&aliquet=mauris&pulvinar=ullamcorper&sed=purus&nisl=sit&nunc=amet&rhoncus=nulla&dui=quisque');
INSERT INTO books_publisher (name , address, city, state_province, country, website) VALUES ('Wikido', '14550 Browning Court', 'Pejë', null, 'Kosovo', 'https://ibm.com/amet/sem/fusce/consequat.js?augue=cum&a=sociis&suscipit=natoque&nulla=penatibus&elit=et&ac=magnis&nulla=dis&sed=parturient&vel=montes&enim=nascetur&sit=ridiculus&amet=mus&nunc=etiam&viverra=vel&dapibus=augue&nulla=vestibulum&suscipit=rutrum&ligula=rutrum&in=neque&lacus=aenean&curabitur=auctor&at=gravida&ipsum=sem&ac=praesent&tellus=id&semper=massa&interdum=id&mauris=nisl&ullamcorper=venenatis&purus=lacinia&sit=aenean&amet=sit');
INSERT INTO books_publisher (name , address, city, state_province, country, website) VALUES ('Dynabox', '92609 Center Parkway', 'An Naşr', null, 'Palestinian Territory', 'http://barnesandnoble.com/rutrum/nulla.json?sed=ipsum&magna=primis&at=in&nunc=faucibus&commodo=orci&placerat=luctus&praesent=et&blandit=ultrices&nam=posuere&nulla=cubilia&integer=curae&pede=mauris&justo=viverra&lacinia=diam&eget=vitae&tincidunt=quam&eget=suspendisse&tempus=potenti&vel=nullam&pede=porttitor&morbi=lacus&porttitor=at&lorem=turpis&id=donec&ligula=posuere&suspendisse=metus&ornare=vitae&consequat=ipsum&lectus=aliquam&in=non&est=mauris&risus=morbi&auctor=non&sed=lectus&tristique=aliquam&in=sit&tempus=amet&sit=diam&amet=in&sem=magna&fusce=bibendum&consequat=imperdiet&nulla=nullam&nisl=orci&nunc=pede&nisl=venenatis&duis=non&bibendum=sodales&felis=sed&sed=tincidunt&interdum=eu&venenatis=felis&turpis=fusce&enim=posuere&blandit=felis&mi=sed&in=lacus&porttitor=morbi&pede=sem&justo=mauris&eu=laoreet&massa=ut&donec=rhoncus&dapibus=aliquet&duis=pulvinar&at=sed&velit=nisl&eu=nunc&est=rhoncus&congue=dui&elementum=vel&in=sem&hac=sed&habitasse=sagittis&platea=nam&dictumst=congue&morbi=risus&vestibulum=semper&velit=porta&id=volutpat&pretium=quam&iaculis=pede&diam=lobortis&erat=ligula&fermentum=sit&justo=amet&nec=eleifend&condimentum=pede&neque=libero&sapien=quis');





INSERT INTO books_publisher (name , address, city, country, state_province, website) VALUES ('Realbuzz', '9973 Mayfield Pass', 'Stockholm', 'Sweden', 'Stockholm', '196.21.32.191');
INSERT INTO books_publisher (name , address, city, country, state_province, website) VALUES ('Zoombeat', '2 Summer Ridge Place', 'Chengyang', 'China', null, '20.203.149.153');
INSERT INTO books_publisher (name , address, city, country, state_province, website) VALUES ('Oba', '43079 Jenna Circle', 'Puncaksempur', 'Indonesia', null, '101.101.232.45');
INSERT INTO books_publisher (name , address, city, country, state_province, website) VALUES ('Mymm', '53 1st Alley', 'Beo', 'Indonesia', null, '26.96.18.119');
INSERT INTO books_publisher (name , address, city, country, state_province, website) VALUES ('Voonder', '2451 Algoma Way', 'Nkandla', 'South Africa', null, '94.110.236.167');
INSERT INTO books_publisher (name , address, city, country, state_province, website) VALUES ('Flipstorm', '7446 Lakewood Drive', 'Weishan', 'China', null, '6.246.154.225');
INSERT INTO books_publisher (name , address, city, country, state_province, website) VALUES ('Cogidoo', '3588 Crowley Road', 'Kapyl’', 'Belarus', null, '244.160.231.250');
INSERT INTO books_publisher (name , address, city, country, state_province, website) VALUES ('Kanoodle', '64 Manitowish Drive', 'Minglanilla', 'Philippines', null, '102.242.86.101');
INSERT INTO books_publisher (name , address, city, country, state_province, website) VALUES ('Livefish', '70771 8th Terrace', 'Yangdian', 'China', null, '200.2.174.196');
INSERT INTO books_publisher (name , address, city, country, state_province, website) VALUES ('Babbleset', '64 Caliangt Crossing', 'Mekarjaya Satu', 'Indonesia', null, '92.88.202.94');
INSERT INTO books_publisher (name , address, city, country, state_province, website) VALUES ('Teklist', '305 Gerald Way', 'Les Sables-d''Olonne', 'France', 'Pays de la Loire', '64.35.132.150');
INSERT INTO books_publisher (name , address, city, country, state_province, website) VALUES ('Edgewire', '41994 Boyd Center', 'Muke', 'Indonesia', null, '109.159.36.185');
INSERT INTO books_publisher (name , address, city, country, state_province, website) VALUES ('Skilith', '5802 Butternut Parkway', 'Ōkawa', 'Japan', null, '238.237.94.34');
INSERT INTO books_publisher (name , address, city, country, state_province, website) VALUES ('Oba', '5 Hagan Place', 'Kudang', 'Indonesia', null, '123.168.247.157');
INSERT INTO books_publisher (name , address, city, country, state_province, website) VALUES ('Agivu', '80 Valley Edge Parkway', 'Teminabuan', 'Indonesia', null, '159.211.29.55');
INSERT INTO books_publisher (name , address, city, country, state_province, website) VALUES ('Riffpath', '7874 Dapin Lane', 'Wolofeo', 'Indonesia', null, '166.174.107.27');
INSERT INTO books_publisher (name , address, city, country, state_province, website) VALUES ('Digitube', '4675 Dwight Hill', 'Spas', 'Ukraine', null, '97.62.177.83');
INSERT INTO books_publisher (name , address, city, country, state_province, website) VALUES ('DabZ', '76 Shasta Court', 'Melíssi', 'Greece', null, '76.140.131.153');
INSERT INTO books_publisher (name , address, city, country, state_province, website) VALUES ('Janyx', '72782 Logan Avenue', 'Wysoka Strzyżowska', 'Poland', null, '68.108.234.34');
INSERT INTO books_publisher (name , address, city, country, state_province, website) VALUES ('Feedbug', '69069 Anthes Lane', 'Hammarö', 'Sweden', 'Värmland', '156.172.228.193');



