# Generated by Django 2.0 on 2018-02-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_remove_cart_taxtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='taxtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
