# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='country',
            field=models.CharField(default='U.S.A', max_length=20),
            preserve_default=False,
        ),
    ]
