# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170526_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='state_province',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
