# Generated by Django 2.0 on 2018-02-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0006_auto_20180222_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=120)),
                ('status', models.CharField(default='created', max_length=120)),
                ('cart', models.ForeignKey(on_delete='Cascade', to='carts.Cart')),
            ],
        ),
    ]
