# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-09 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170910_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='father_name',
            field=models.CharField(blank=True, max_length=254, verbose_name="Father's name of User"),
        ),
        migrations.AlterField(
            model_name='user',
            name='mother_name',
            field=models.CharField(blank=True, max_length=254, verbose_name="Mother's name of User"),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Name of User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Present Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='present_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Present Address'),
        ),
    ]
