# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-09 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170910_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='M', max_length=253, verbose_name='Gender'),
        ),
    ]
