# Generated by Django 2.2.1 on 2019-05-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_risktype_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risktype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
