# Generated by Django 2.2.1 on 2019-05-31 17:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_auto_20190531_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='risk_attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='risktype',
            name='attribute_collection',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
