# Generated by Django 2.2.3 on 2019-08-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cart_ordered'),
        ('orders', '0003_auto_20190811_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(blank=True, null=True, to='carts.Cart'),
        ),
    ]
