PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# For C source code
BASE <https://semantic-web.netlify.com/c_source_ontology/>

# For Javascript Code
BASE <https://semantic-web.netlify.com/js_source_ontology/>


# 1. Total number of conditional structures

SELECT (COUNT(?subject) AS ?c) WHERE {
    ?subject rdf:type <ConditionalStructure>
}

# Expected Result on C code: 3
# Expected Result on JS code: 3

# 2. Total number of repetitive structures

SELECT (COUNT(?subject) AS ?c) WHERE {
    ?subject rdf:type <RepetitiveStructure>
}

# Expected Result on C code: 3
# Expected Result on JS code: 3

# 3. Total number of variables

SELECT (COUNT(?subject) AS ?c) WHERE {
    ?subject rdf:type <Variable>
}


# Expected Result on C code: 4
# Expected Result on JS code: 4

# 4. Total number of conditional structures included in repetitive structures


SELECT (COUNT(?subject) AS ?c) WHERE {
    ?object rdf:type <RepetitiveStructure> .
    ?subject <is_included_in> ?object .
    ?subject rdf:type <ConditionalStructure>
}

# Expected Result on C code: 3
# Expected Result on JS code: 3

# 5. Total number of repetitive structures included in repetitive structures

SELECT (COUNT(?subject) AS ?c) WHERE {
    ?object rdf:type <RepetitiveStructure> .
    ?subject <is_included_in> ?object .
    ?subject rdf:type <RepetitiveStructure>
}

# Expected Result on C code: 0
# Expected Result on JS code: 0

# 6.  Total number of system functions called

SELECT (COUNT(?subject) AS ?c) WHERE {
    ?subject rdf:type <SystemFunction>
}

# Expected Result on C code: 5
# Expected Result on JS code: 4

# 7.  Total number of system functions called in conditional structures

SELECT (COUNT(?subject) AS ?c) WHERE {
    ?object rdf:type <ConditionalStructure> .
    ?subject <is_included_in> ?object .
    ?subject rdf:type <SystemFunction>
 }

 # Expected Result on C code: 1
 # Expected Result on JS code: 1

# 8. Total Number of repetative structures

SELECT (COUNT(?subject) AS ?c) WHERE {
    ?object rdf:type <RepetitiveStructure> .
    ?subject <is_included_in> ?object .
    ?subject rdf:type <SystemFunction>
}

# Expected Result on C code: 4
# Expected Result on JS code: 3
